todo/tasklist/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    path('<int:cur_year>/<int:week_num>/', views.index, name='home_with_week'),
    path('create_task/<int:cur_year>/<int:week_num>/<slug:task_date>/', views.create_task, name='create_task'),
    path('delete_task/<int:cur_year>/<int:week_num>/<int:task_id>/', views.delete_task, name='delete_task'),
    path('is_completed_task/<int:cur_year>/<int:week_num>/<int:task_id>/',
         views.is_completed_task, name='is_completed_task'),

]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

from tasklist.views import page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasklist.urls')),
    path('users/', include('users.urls', namespace='users'))

]


handler404 = page_not_found

todo/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
]

todo/tasklist/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Task(models.Model):
    text = models.CharField(max_length=255)
    task_date = models.DateField()
    is_completed = models.BooleanField(default=False)

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='posts', null=True)

    def __str__(self):
        return self.text

todo/users/models.py
from django.db import models

# Create your models here.

todo/tasklist/forms.py
from django import forms
from .models import Task


class CreateTaskForm(forms.ModelForm):
    task_date = forms.DateInput()

    class Meta:
        model = Task
        fields = ['text', 'task_date', 'is_completed', 'user']
        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите текст задания'}),
        }

todo/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ['username', 'password']


class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(label="Логин")
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Пароли не совпадают!")
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

todo/tasklist/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotFound
from django.shortcuts import render, redirect

from .forms import CreateTaskForm
from .models import Task


day_today = datetime.date.today().strftime('%A, %d %B %Y')
iso_date = datetime.date.today().isocalendar()


@login_required
def index(request, cur_year=iso_date[0], week_num=iso_date[1]):
    if week_num >= 53:
        cur_year += 1
        week_num = 1
    elif week_num <= 0:
        cur_year -= 1
        week_num = 52

    day_list = [datetime.date.fromisocalendar(cur_year, int(week_num), x) for x in range(1, 8)]

    task_list = Task.objects.filter(user_id=request.user).all()

    data = {
        'title': 'Главная страница',
        'day_list': day_list,
        'task_list': task_list,
        'week_num': week_num,
        'day_today': day_today,
        'cur_year': cur_year,

    }
    return render(request, 'tasklist/index.html', context=data)


@login_required
def create_task(request, cur_year, week_num, task_date):
    if request.method == 'POST':
        new_post = dict(**request.POST)
        new_post['task_date'] = datetime.datetime.strptime(task_date, '%Y-%m-%d').date()
        new_post['user'] = request.user.id
        new_post['text'] = new_post['text'][0]
        form = CreateTaskForm(new_post)
        if form.is_valid():
            form.save()
            return redirect('home_with_week', cur_year=cur_year, week_num=week_num)
    else:
        form = CreateTaskForm()

    data = {
        'title': 'Создание задания',
        'week_num': week_num,
        'task_date': task_date,
        'form': form,
        'cur_year': cur_year,

    }
    return render(request, 'tasklist/create_task.html', context=data)


@login_required
def delete_task(request, cur_year, week_num, task_id):
    task = Task.objects.get(pk=task_id)
    if task is None:
        pass

    task.delete()
    return redirect('home_with_week', cur_year=cur_year, week_num=week_num)


def is_completed_task(request, cur_year, week_num, task_id):
    task = Task.objects.get(pk=task_id)
    if task.is_completed == 0:
        task.is_completed = 1
    else:
        task.is_completed = 0
    task.save()
    return redirect('home_with_week', cur_year=cur_year, week_num=week_num)


def page_not_found(request, exception):
    return HttpResponseNotFound('<h1> Страница не найдена</h1>')

todo/users/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render

from django.urls import reverse_lazy

from users.forms import RegisterUserForm


class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'
    extra_context = {'title': "Авторизация"}

    def get_success_url(self):
        return reverse_lazy('home')


def register(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)  # создание объекта без сохранения в БД
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'users/register_done.html')
    else:
        form = RegisterUserForm()
    return render(request, 'users/register.html', {'form': form})

todo/tasklist/templates/tasklist/create_task.html
{% extends 'base.html' %}

{% block content %}

    {% include 'menu_create_task.html' %}

    <div class="container">
        <form action="" method="POST">
            <div class="container text-center">
                <div class="row">
                    <div class="col align-self-center">
                        {% csrf_token %}

                        <div class="input-group">
                            {{ form.text }}
                            <button class="btn btn-outline-secondary" type="submit">Создать!</button>

                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

todo/tasklist/templates/tasklist/index.html
{% extends 'base.html' %}
{% block content %}
    {% include 'menu.html' %}

    <div class="container">
        <div class="row gx-0">
            {% if user.is_authenticated %}
                {% for val in day_list|slice:':-1' %}
                    <div class="col-lg-2">
                        <ul class="list-group">
                            <li class="list-group-item">
                                {{val|date:'D, d b Y'}}
                            </li>
                            {% for task in task_list %}
                                {% if task.task_date == val %}
                                    {% include 'modal_form.html' %}
                                {% endif %}
                            {% endfor %}
                            <li class="list-group-item">
                                <a href="/create_task/{{ cur_year }}/{{week_num}}/{{ val|date:'Y-m-d' }}" class="text" >Добавить задание</a>
                            </li>
                        </ul>
                        {% if val|date:'D' == 'Сб' %}
                            <ul class="list-group">
                                <li class="list-group-item">
                                    {{ day_list|last|date:'D, d b Y' }}
                                </li>
                                {% for task in task_list %}
                                    {% if task.task_date == day_list|last %}
                                        {% include 'modal_form.html' %}
                                    {% endif %}
                                {% endfor %}
                                <li class="list-group-item">
                                    <a href="/create_task/{{ cur_year }}/{{week_num}}/{{ day_list|last|date:'Y-m-d' }}" class="text" >Добавить задание</a>
                                </li>
                            </ul>
                        {% endif %}
                    </div>
                {% endfor %}
            {% else %}
                <p>Чтобы повысить вашу производительность, ежедневник построен на основе недельного календаря без почасового планирования. Мы бы сказали, что это лучший вид, чтобы организовать свою жизнь и работу без стресса.</p>
            {% endif %}
        </div>
    </div>

{% endblock %}

todo/templates/base.html
<!doctype html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{ title }}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    </head>
    <body>

        {% block content %}
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    </body>
</html>

todo/templates/menu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">
      {% if user.is_authenticated %}
      {{ day_today }}
      {% else %}
      Добро пожаловать
      {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/{{ cur_year }}/{{ week_num|add:'-1'}}"> <<< </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/{{ cur_year }}/{{ week_num|add:'1'}}"> >>> </a>
          </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
          <li class="nav-item">
              <span class="nav-link"> {{user.username}} </span>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
          </li>
        {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
            </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

todo/templates/menu_create_task.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">{{title}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      </ul>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
            <li class="nav-item">
                <span class="nav-link"> {{user.username}} </span>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
            </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

todo/templates/modal_form.html
<!-- Button trigger modal -->
                                    <li type="button" class="list-group-item list-group-item-action" data-bs-toggle="modal" data-bs-target="#{{task.id}}">
                                        <div class="col text-truncate">
                                            {% if task.is_completed == 1 %}
                                                <s>{{task.text}}</s>
                                            {% else %}
                                                {{task.text}}
                                            {% endif %}
                                        </div>
                                    </li>
                                    <!-- Modal -->
                                    <div class="modal fade" id="{{task.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    {{task.text}}
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><a href="/delete_task/{{ cur_year }}/{{week_num}}/{{task.id}}">Удалить</a></button>
                                                    <button type="button" class="btn btn-success" data-bs-dismiss="modal"><a href="/is_completed_task/{{ cur_year }}/{{week_num}}/{{task.id}}">Готово!</a></button>
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

todo/users/templates/users/login.html
{% extends 'base.html' %}
 
{% block content %}
{% include 'menu.html' %}
<h1>Авторизация</h1>
 
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {{ form.as_p }}
    <p ><button type="submit">Войти</button></p>
</form>
 
{% endblock %}

todo/users/templates/users/register.html
{% extends 'base.html' %}
 
{% block content %}
{% include 'menu.html' %}
<h1>Регистрация</h1>
 
<form method="post">
    {% csrf_token %}
<input type="hidden" name="next" value="{{ next }}" />
    {{ form.as_p }}
    <p ><button type="submit">Регистрация</button></p>
</form>
 
{% endblock %}

todo/users/templates/users/register_done.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Добро пожаловать!</h1>
 
<p >Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой <a href="{% url 'users:login' %}">ссылке</a>
</p>
{% endblock %}